---
# Command: `-L scholarly-metadata.lua -L format-authors.lua`
# institute:
#   # OR Faculty of Computers and Artificial Intelligence, Benha University (See whether to remove Comma in [Intelligence, Benha] or not)
#   - first: Faculty of Computer Science, Benha University

#   # - second: Second, Newer Company
# author:
#   - Mohamed Emary:
#       institute:
#         - first
#       correspondence: yes
#       email: mohamed21074@fci.bu.edu.eg

# author: [Mohamed Emary]
# author:
#   [
#     Mohamed Emary,
#     Mohamed Abdelfattah,
#     Abdelfattah Zakaria,
#     Shrouk Elsayed,
#     Dalia Abdallah,
#     Sara Reda,
#   ]

# author:
# - Mohamed Ahmed Emary^[**Benha Faculty of Computers and Artificial Intelligence, <mohamed21074@fci.bu.edu.eg>**]
# date: \today

papersize: a4
# toc-depth:
toc: true
lof: true
lot: true

geometry:
  - top=20mm
  - bottom=20mm
  - right=20mm
  - left=20mm

# fontfamily:
# documentclass: extarticle
fontsize: 12pt
numbersections: yes
fig_caption: true
autoEqnLabels: true
theme: copenhagen
# linkcolor table of figures links and document inner links and urlcolor for regular links
linkcolor: black
urlcolor: blue

include-before:
  # Pagebreak after main title
  # - '`\newpage{}`{=latex}'

header-includes:
  - \input{/mnt/movies-and-photos/repos/dotfiles/pandoc/macros.tex}
  # Adjust the vertical spacing between table rows
  - \renewcommand{\arraystretch}{1.3}

  # this controls the spacing between bullet list items
  # - \usepackage{enumitem}
  # - \setlist[itemize]{parsep=8pt}
  # - \setlist[enumerate]{itemsep=15pt}

  # # Fancy Header
  # - \usepackage{fancyhdr}
  # - \pagestyle{fancy}
  # - \fancyhf{}
  # - \lhead{\leftmark}
  # - \usepackage{lastpage}
  # - \usepackage{fancyhdr}
  # - \pagestyle{fancy}
  # - \fancypagestyle{plain}{}
  # - \fancyhf{}
  # - \renewcommand{\headrulewidth}{0pt}
  # - \rfoot{Page \thepage \hspace{1pt} of \pageref{LastPage}}

  # Code blocks linebreaks
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  # Inline code linebreaks (not working)
  # - \usepackage[htt]{hyphenat}

  # # Graphs & function plots
  #  - \usepackage{pgfplots}
  #  - \usepackage{tikz}

  # tcolorbox package
  - \usepackage[most]{tcolorbox}

  # Figures with captions
  - \usepackage{float}
  - \makeatletter
  - \def\fps@figure{H}
  - \makeatother

  # lettrine package to make first letter larger
  - \usepackage{lettrine}
  - \renewcommand{\LettrineTextFont}{\normalfont}
  # - \usepackage{Typocaps} # The package need to be changed to use another font
  # - \renewcommand{\LettrineFontHook}{\Typocapsfamily} # \Typocapsfamily is the font if you want to change

  # Definition Box
  - \usepackage{xcolor}
  - \usepackage{tikz}
  - \usepackage{lipsum}
  - \definecolor{gre}{RGB}{101, 191, 127}
  - \definecolor{gree}{RGB}{7, 135, 44}
  - \usepackage[most]{tcolorbox}

  - \newtcolorbox{defin}{colback=green!10,enhanced,title=Definition,attach boxed title to top left={xshift=-4mm},boxrule=0pt,after skip=1cm,before skip=1cm,right skip=0cm,breakable,fonttitle=\bfseries,toprule=0pt,bottomrule=0pt,rightrule=0pt,leftrule=4pt,arc=0mm,skin=enhancedlast jigsaw,sharp corners,colframe=gree,colbacktitle=gre,boxed title style={frame code={\fill[gre](frame.south west)--(frame.north west)--(frame.north east)--([xshift=3mm]frame.east)--(frame.south east)--cycle;\draw[line width=1mm,gre]([xshift=2mm]frame.north east)--([xshift=5mm]frame.east)--([xshift=2mm]frame.south east);\draw[line width=1mm,gre]([xshift=5mm]frame.north east)--([xshift=8mm]frame.east)--([xshift=5mm]frame.south east);\fill[green!40](frame.south west)--+(4mm,-2mm)--+(4mm,2mm)--cycle;}}}

  - \usepackage{caption}
  - \usepackage{tabularray}
  - \UseTblrLibrary{booktabs}
  #  - \setlength{\heavyrulewidth}{1.5pt}

  # Used for tables with merged cells
  - \usepackage{multirow}

  # Use times new roman font
  - \usepackage{times}
  # - \usepackage{mathptmx}
  # - \usepackage{newtxtext}

  # - \usepackage{mathptmx}
  # - \usepackage[scaled=.90]{helvet}
  # - \usepackage{courier}

  # - \usepackage{fontspec}
  # - \setmainfont{Times New Roman}

  # For line spacing
  - \usepackage{setspace}

  # Fancy Header
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{2pt}
  - \fancyhead[l]{\textbf{\large \leftmark}}
  - \rfoot{\thepage}
  # - \rfoot{\thepage}

  - \usepackage{skillicons} # \photosymbol{JavaScript}
  - \usepackage{fontawesome} # \faGithub

  - \usepackage{algorithm}
  - \usepackage{algpseudocode}
---

